#!/usr/bin/env python3
"""Generate a boot key override header for production bootloader builds."""

from __future__ import annotations

import argparse
import pathlib
import subprocess
import textwrap


def parse_aes_key(value: str) -> bytes:
    text = value.strip().replace(":", "").replace(" ", "")
    data = bytes.fromhex(text)
    if len(data) != 16:
        raise argparse.ArgumentTypeError(f"expected 16 AES key bytes, got {len(data)}")
    return data


def openssl_modulus(public_key: pathlib.Path) -> bytes:
    commands = [
        ["openssl", "rsa", "-pubin", "-in", str(public_key), "-modulus", "-noout"],
        ["openssl", "rsa", "-in", str(public_key), "-modulus", "-noout"],
    ]
    last_error = ""

    for command in commands:
        result = subprocess.run(
            command,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if result.returncode == 0:
            output = result.stdout.strip()
            prefix = "Modulus="
            if not output.startswith(prefix):
                raise RuntimeError(f"unexpected openssl modulus output: {output!r}")
            modulus = bytes.fromhex(output[len(prefix):])
            if len(modulus) != 256:
                raise RuntimeError(f"expected RSA-2048 modulus, got {len(modulus) * 8} bits")
            return modulus
        last_error = result.stderr.strip()

    raise RuntimeError(f"failed to read RSA public modulus: {last_error}")


def c_array(data: bytes, indent: str = "    ") -> str:
    lines = []
    for offset in range(0, len(data), 16):
        chunk = data[offset: offset + 16]
        values = ", ".join(f"0x{byte:02X}" for byte in chunk)
        lines.append(f"{indent}{values}")
    return ",\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Affine boot key override header")
    parser.add_argument("--public-key", required=True, type=pathlib.Path, help="RSA-2048 public or private PEM")
    parser.add_argument("--aes-key-hex", required=True, type=parse_aes_key, help="AES-128 key as 32 hex characters")
    parser.add_argument("--out", required=True, type=pathlib.Path, help="output header path")
    args = parser.parse_args()

    modulus = openssl_modulus(args.public_key)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        textwrap.dedent(
            f"""\
            /* Generated by tools/generate_boot_keys_header.py. Do not commit. */
            static const uint8_t g_boot_manifest_rsa2048_modulus[BOOT_RSA2048_SIGNATURE_SIZE] = {{
            {c_array(modulus)}
            }};

            static const uint8_t g_boot_stream_aes128_key[BOOT_AES128_KEY_SIZE] = {{
            {c_array(args.aes_key_hex)}
            }};
            """
        ),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
